### ISSUE TITLE
PHP rename function doesn't copy folders recursively across separated volumes

### ISSUE THREAD

**Issue by AntzCode** [AntzCode/opensource-socialnetwork#10]
## Outline of the problem

According to a [bug at PHP.net](https://bugs.php.net/bug.php?id=54097): "when a user tries to rename a directory accross filesystems, they are presented with this warning:

> PHP Warning:  rename(): The first argument to copy() function cannot be a 
> directory in Command line code on line 1

There is a link to another report of [the same bug on Launchpad.net](https://bugs.launchpad.net/ubuntu/+source/php5/+bug/723330), where it is said:

> Basically since your /tmp is a different partition than your home dir, php must emulate the low level unix rename by copying the file. The copy is failing because the source is a dir, and copy doesn't accept directories.
> 
> This is a bug, with an unclear resolution. 

Another member had noted three years ago "This problem has apparently been outstanding for ~7 years!".

The PHP team seems to think that the work-around solutions are easier and preferable than trying to fix the bug in PHP. 

## How it affects this project

OSSN has been designed to store uploaded files outside of the webserver root so that uploaded files cannot be accessed via the webserver unless OSSN has ascertained that the user has permission to view the file. OSSN acts as the security layer for the content.

When OSSN installs, it checks to make sure that the ```ossn_data``` directory is not within the webserver root. If the ossn_data directory resides within the webserver root, it refuses to install. Therefore the problem cannot be easily resolved by such a simple configuration.

The docker-compose.yml configuration sets two separate volumes for this purpose: 
```
./www > /var/www/html (the web root)
./ossn_data > /var/www/ossn_data (system data outside of the web root)
```

## Impacts

* This problem appears whenever a directory is copied between the web server and the ossn_data volumes.
* All uploads of components and themes through the Administrator Control Panel are affected because the installer first extracts the .zip file into the ```ossn_data/tmp``` directory before it transfers the contents to their appropriate place in the web root.
* This is a critical bug that prevents the installation of components and themes on the docker installation.

**Comment by AntzCode** [comment]
> @AntzCode thanks for working on docker image for OSSN :) I am not docker expert but is there anyway if ossn_data directory is owned by apache user then php can able to write inside this directory?

@lianglee it's not a file permissions matter in this case, it is a bug in PHP when using the ```copy()``` or ```rename()``` functions to move a *directory* from one *volume* to a different volume. The rename and copy functions work as expected when moving files across volumes or when moving directories within the same volume, so it is only if the ```$from``` and ```$to``` directories are mounted on different volumes as in the case with a typical docker installation. 

The answer is actually quite simple though, if you see the attached patch. It just means that we have to use the existing method for moving the folders and only use the rename function for the files. I can't see how it might be a problem.

[aa801418980bc0ce28529f292c4f3031f1ba5ee4.patch.txt](https://github.com/AntzCode/opensource-socialnetwork/files/6935952/aa801418980bc0ce28529f292c4f3031f1ba5ee4.patch.txt)

**Comment by lianglee** [comment]
Yes I understand that if $to and $from are different volumes it didn't work.  I haven't seen patch before as its done after my last reply.

**Comment by AntzCode** [comment]
I have created an issue in the upstream project to recommend that these changes are propagated in the OSSN core:

https://github.com/opensource-socialnetwork/opensource-socialnetwork/issues/1985

Closing this issue as fixed.
